### ISSUE TITLE
Missing conf_file.txt

### ISSUE THREAD

**Issue by yashu88** [aig-upf/automated-programming-framework#1]
hello sir,

I want to compile this project on my machine.

But there is no conf_file.txt file available on uploaded github.

Kindly help me out.

Thank you and Regards,
Yashashree

**Comment by ertsiger** [comment]
Hi @yashu88,

the configuration files are not necessarily named `conf_file.txt`. For example, the file `automated-programming-framework/config/aij17/ca/blocksworld.txt` is a configuration file you can use for experimenting. The same occurs with `automated-programming-framework/config/jair17/4corners_5_4.txt`, for instance.

Hope it helps :)

**Comment by yashu88** [comment]
Thank you very much for help. 

Best regards.
