### ISSUE TITLE
Understanding the output of the generalized programming framework

### ISSUE THREAD

**Issue by ivan-gavran** [aig-upf/automated-programming-framework#5]
Hi,
I would like to understand the output of the planner properly. 
From what I know thus far, the actual steps of the agent can be found as the output of running `main` on a configuration file, whereas a program can be found in the file `program.txt`. They both use some numerical coding that I don't fully understand.

As an example, let's have a look at the content of `program.txt` for a task in which a robot starting at `(1,1)` has to reach `(3,5)`, with 4 (generalized) steps:
INS-MOVE-0 X1 Y1 X1 Y2 ROW-0
GOTO-0-1-3
COND-ROBOT-AT-0-1 X1 Y5 ROW-0
GOTO-0-3-0
COND-ROBOT-AT-0-3 X3 Y5 ROW-0
INS-TURN-RIGHT-2 NORTH EAST X1 Y5 ROW-0
INS-END-4 ROW-0

I understand this program to mean
```
0. move
1. if robot not at (1,5) goto 3
2. turn right
3. if robot not at (3,5) goto 0
4. end
```
- Every INS- prefixed command has an additional number (e.g. INS-MOVE-0). I presume this number denotes the line in the program. 
- Every COND- prefixed command has two additional numbers (e.g. COND-ROBOT-AT-0-1 X1 Y5). I concluded that the second of these two numbers (1, in this case) denotes the line of code. But what is the meaning of the first number (0, in this case)?
- every GOTO- prefixed command has three additional numbers (e.g. GOTO-0-1-3). I concluded that the third of these numbers (3, in this case) is the line number of where the program execution should continue. But what is the meaning of the first two numbers (0 and 1)?

Is my interpretation of the program correct? And what is the role of the numbers that I do not understand yet?

For completeness: the config, domain and problem files can be found in [my fork of the project](https://github.com/gergia/automated-programming-framework/tree/understandingOutput): [config](https://github.com/gergia/automated-programming-framework/blob/understandingOutput/config/karel/karel-hoc.txt), [domain](https://github.com/gergia/automated-programming-framework/blob/understandingOutput/domains/karel/domain-hoc.pddl), [problem](https://github.com/gergia/automated-programming-framework/blob/understandingOutput/domains/karel/problem1-hoc.pddl)

Thanks in advance for guiding me through many interesting parts of this project.

**Comment by jsego** [comment]
Hi,

The numbers appended to instructions will depend on the compilation mode, which in this case is PLPR (Planning Programs).
There are 3 kinds of instructions:
a) Sequential instructions (from the actions in the planning domain)
b) Conditional gotos (splitted into gotos and conditions)
c) End instructions (terminating condition)

The number appended to instructions a) and c) is the line where they are programmed. If there are more than one procedure, the first number will be the procedure where they are programmed and the second the line in that procedure.
Conditions and gotos have the form COND-P-X and GOTO-P-X-Y respectively, where P is the procedure where they are programmed (always 0 if there is only one procedure), X is the programmed line, and Y is the destination line if the condition evaluates to false.

Your interpretation of the program looks correct.

**Comment by ivan-gavran** [comment]
Great, thanks for the explanation!
