### ISSUE TITLE
Failed to find a plan for two same problems

### ISSUE THREAD

**Issue by ivan-gavran** [aig-upf/automated-programming-framework#7]
Hi,
While experimenting with the framework, I encountered a curious issue: I created two instances of exactly the same problem. The generalized planner is able to solve instances individually, but cannot find a solution that would work for both of them.

It actually reports that there is not solution:

> Expanded 0 state(s).
Reopened 0 state(s).
Evaluated 1 state(s).
Evaluations: 1
Generated 0 state(s).
Dead ends: 1 state(s).

A minimal example can be found in my clone: 
- [pddl files](https://github.com/gergia/automated-programming-framework/tree/twoSameProblems/domains/karel/debug)
- [config files](https://github.com/gergia/automated-programming-framework/tree/twoSameProblems/config/karel)

Do you have an idea what is happening here and why is the search stopped immediately? Is there some problem formulation/config formulation issue?

**Comment by jsego** [comment]
Hi,

Here a list of typos/improvements:
- An object must be either in the constants of the domain or in the instance file but not both (e.g. north, south, ... are duplicated)
- The domain in the config file must be: domains/karel/debug/karelDomain.pddl
- There are some missing fluents in the instances:  (succ x0 x1) (succ y0 y1)

With that said, both instances should be solvable in a lifted planning program of 4 lines.

Best,

**Comment by ivan-gavran** [comment]
Thanks for the reply, @jsego .
It seems that the things/problems you noticed in the code are not the cause of the problem
 - for some reason, I have to put north, south,... to be duplicated. I do not know why, but if I do not do so, I get a parser error (and, indeed, when I am working with any other planner, I have to omit those duplicates). --> I pushed the files illustrating this, with this [config file](https://github.com/gergia/automated-programming-framework/blob/twoSameProblems/config/karel/confSingleProblemNoDuplicates.txt) 
 - you are right, the domain mistake was a typo (occurred when I was cleaning up the file to be more readable. I had locally the same file instance with the other name). Now I changed this so that one can properly reproduce the issue from the repo only. (Sorry for that sloppiness.)
 - you are right about missing fluents as well: but they are also not the reason for the failure. Indeed, the robot's initial position was `(x1 y1)` so the missing links between `x0` and `x1` should not affect planning. I added the missing fluents to avoid confusion and the problem persists.

I am copying below the full output that I get when trying to get a lifter planning program (perhaps this gives you a better idea of what goes wrong).

```
INFO     Running search (release).
INFO     search stdin: output.sas
INFO     search time limit: None
INFO     search memory limit: None
INFO     search command line string: /home/gavran/problems/machineTeaching/karel/automated-programming-framework/PLANNERS/fast-downward/builds/release/bin/downward --evaluator 'hlm=lmcount(lm_factory=lm_rhw(reasonable_orders=true),transform=adapt_costs(one),pref=false)' --evaluator 'hff=ff(transform=adapt_costs(one))' --search 'lazy_greedy([hff,hlm],preferred=[hff,hlm],cost_type=one,reopen_closed=false)' --internal-plan-file sas_plan < output.sas
reading input... [t=2.5332e-05s]
done reading input! [t=7.3571e-05s]
Initializing landmarks count heuristic...
Initializing Exploration...
Generating landmarks using the RPG/SAS+ approach
approx. reasonable orders
approx. obedient reasonable orders
Removed 0 reasonable or obedient reasonable orders
Landmarks generation time: 2.6849e-05s
Discovered 2 landmarks, of which 0 are disjunctive and 0 are conjunctive 
1 edges
Simplifying 0 unary operators... done! [0 unary operators]
time to simplify: 6.012e-06s
Initializing additive heuristic...
Initializing FF heuristic...
Building successor generator...done! [t=0.00116304s]
peak memory difference for successor generator creation: 0 KB
time for successor generation creation: 3.42e-06s
Variables: 1
FactPairs: 2
Bytes per state: 4
Conducting lazy best first search, (real) bound = 2147483647
1 initial landmarks, 1 goal landmarks
Initial heuristic value for ff(transform = adapt_costs(one)): infinity
Completely explored state space -- no solution!
Actual search time: 1.4721e-05s [t=0.00128652s]
Expanded 0 state(s).
Reopened 0 state(s).
Evaluated 1 state(s).
Evaluations: 1
Generated 0 state(s).
Dead ends: 1 state(s).
Number of registered states: 1
Int hash set load factor: 1/1 = 1
Int hash set resizes: 0
Search time: 4.6172e-05s
Total time: 0.00129018s
Search stopped without finding a solution.
Peak memory: 22180 KB
Remove intermediate file output.sas
search exit code: 12

Driver aborting after search

```

**Comment by jsego** [comment]
Hi @gergia,

It seems the issue comes from constants and objects. Since north, south, west and east directions are used in the action models, they must be included as constants of the domain instead of instance objects.

Also, I suggest you to use the names turn-left and turn-right for actions, and delete the ?x ?y parameters from both actions, because the robot location is not required to turn in one direction or another (and that will decrease the number of grounded actions).

Best,

**Comment by ivan-gavran** [comment]
Thanks @jsego ,

you are right: declaring north, south... in the domain but not in actions resolves the syntax issue.
I also took your advice and removed ?x ?y parameters from turning.
However, these changes do not fix the original problem: it is still the case that the planner is able to find a plan for a single problem, but cannot find it for the two instances of the same problem. (It is more than that: it claims to have ended up in a dead end).

All the changes are visible in [this commit](https://github.com/gergia/automated-programming-framework/commit/3386ff868b412894363aa0ca9c7ee403856d39e7) and the described behavior can be reproduced by running
- `./main config/karel/confSingleProblem.txt` (single file, solution is found)
- `./main config/karel/confTwoProblems.txt` (two same files, no solution is found)

**Comment by jsego** [comment]
Hi @gergia,

I have done some tests and detected that the planner is not doing some default work, e.g. applying negative effects before positive ones. Specifically, this happens for the ( robot-facing north ), which is deleted in the REPEAT-END-MAIN-0-4 action but not added for the next test instance as expected (the robot losses its direction between instances).

A workaround for this weird behavior is to define the robot location and direction in one fluent (there could be more efficient ways to tackle this issue). I leave here the domain and instance (you can try your go action instead of the new defined go).
[karelDomain.txt](https://github.com/aig-upf/automated-programming-framework/files/7220108/karelDomain.txt)
[problem1.txt](https://github.com/aig-upf/automated-programming-framework/files/7220107/problem1.txt)

Best,

**Comment by ivan-gavran** [comment]
Hi @jsego ,

Thanks for your answer - I confirm that this approach resolves the problem. (For future reference of anybody following this issue: [this commit](https://github.com/gergia/automated-programming-framework/commit/5b2adad158c7fe14f71e86c4777e7dcdc2e2efeb) of the branch with debug examples)

I leave it up to you whether to close the issue immediately or you want to leave it open until the problem with applying negative effects is resolved.

**Comment by jsego** [comment]
Hi @gergia,

Since the bug is not in the GP framework I close this issue.
Thank you for detecting the problem with the planner software.
